/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package typegame;

import java.awt.Color;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import java.io.File;
import java.nio.file.FileSystems;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
 
  
 
public class Shop extends javax.swing.JFrame {

    private static TypeGame baseGame;
    /**
     * Creates new form Shop
     */
    public Shop(TypeGame theOne) {
        initComponents();
        setLocationRelativeTo(null);
        baseGame=theOne;
        disallowEdits();
        setDescriptions();
    }
    //makes all description boxes uneditable
    public void disallowEdits(){
        damageDescription.setEditable(false);
        armourDescription.setEditable(false);
        healthDescription.setEditable(false);
        comboDescription.setEditable(false);
        moneyBox.setEditable(false);
    }
    //adds upgrade descriptions for upgrades and sets money box text
    public void setDescriptions(){
        damageDescription.setText(baseGame.getUpgradesList().get(0).getDescription()+baseGame.getUpgradesList().get(0).getCost(1));
        healthDescription.setText(baseGame.getUpgradesList().get(1).getDescription()+baseGame.getUpgradesList().get(1).getCost(1));
        armourDescription.setText(baseGame.getUpgradesList().get(2).getDescription()+baseGame.getUpgradesList().get(2).getCost(1));
        comboDescription.setText(baseGame.getUpgradesList().get(3).getDescription()+baseGame.getUpgradesList().get(3).getCost(1));
        moneyBox.setText("gold: " + Integer.toString(baseGame.getMoney()));
    }
    //checks if String can be converted to int
    public static boolean canParse(String s){
            try{
                Integer.parseInt(s);
                return true;
            }
            catch(NumberFormatException e){
                return false;
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Damage = new javax.swing.JButton();
        Armour = new javax.swing.JButton();
        Health = new javax.swing.JButton();
        damageField = new javax.swing.JTextField();
        armourField = new javax.swing.JTextField();
        healthField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        damageDescription = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        armourDescription = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        healthDescription = new javax.swing.JTextPane();
        comboButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        comboDescription = new javax.swing.JTextPane();
        shopExit = new javax.swing.JButton();
        moneyBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Damage.setText("Damage UP");
        Damage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DamageActionPerformed(evt);
            }
        });

        Armour.setText("Armour UP");
        Armour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArmourActionPerformed(evt);
            }
        });

        Health.setText("Health UP");
        Health.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthActionPerformed(evt);
            }
        });

        damageField.setText("# to buy");
        damageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damageFieldActionPerformed(evt);
            }
        });

        armourField.setText("# to buy");

        healthField.setText("# to buy");

        jScrollPane1.setViewportView(damageDescription);

        jScrollPane3.setViewportView(armourDescription);

        jScrollPane4.setViewportView(healthDescription);

        comboButton.setText("Unlock new combo");
        comboButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(comboDescription);

        shopExit.setText("Exit shop");
        shopExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Damage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(damageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(shopExit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Armour, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)
                                                .addComponent(armourField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Health, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(healthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(moneyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Damage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Armour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Health, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(damageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(armourField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(healthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addComponent(comboButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shopExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(moneyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DamageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DamageActionPerformed
        // TODO add your handling code here:
        if(canParse(damageField.getText())){
            if((baseGame.getMoney())>=baseGame.getUpgradesList().get(0).getCost(Integer.parseInt(damageField.getText()))){
            baseGame.removeMoney(baseGame.getUpgradesList().get(0).getCost(Integer.parseInt(damageField.getText())));
            baseGame.getUpgradesList().get(0).buyUpgrade(Integer.parseInt(damageField.getText()));
            moneyBox.setText("gold: " + Integer.toString(baseGame.getMoney()));
            }
        }
    }//GEN-LAST:event_DamageActionPerformed

    private void ArmourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArmourActionPerformed
        // TODO add your handling code here:
        if(canParse(armourField.getText())){
            if((baseGame.getMoney())>=baseGame.getUpgradesList().get(2).getCost(Integer.parseInt(armourField.getText()))){
            baseGame.removeMoney(baseGame.getUpgradesList().get(2).getCost(Integer.parseInt(armourField.getText())));
            baseGame.getUpgradesList().get(2).buyUpgrade(Integer.parseInt(armourField.getText()));
            moneyBox.setText("gold: " + Integer.toString(baseGame.getMoney()));
            }
        }
    }//GEN-LAST:event_ArmourActionPerformed

    private void HealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthActionPerformed
        // TODO add your handling code here:
        if(canParse(healthField.getText())){
            if((baseGame.getMoney())>=baseGame.getUpgradesList().get(1).getCost(Integer.parseInt(healthField.getText()))){
            baseGame.removeMoney(baseGame.getUpgradesList().get(1).getCost(Integer.parseInt(healthField.getText())));
            baseGame.getUpgradesList().get(1).buyUpgrade(Integer.parseInt(healthField.getText()));
            moneyBox.setText("gold: " + Integer.toString(baseGame.getMoney()));
            }
        }
    }//GEN-LAST:event_HealthActionPerformed

    private void damageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_damageFieldActionPerformed

    private void shopExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        baseGame.updateGold();
        baseGame.setVisible(true);
    }//GEN-LAST:event_shopExitActionPerformed

    private void comboButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboButtonActionPerformed
        // TODO add your handling code here:
            if((baseGame.getMoney())>=baseGame.getUpgradesList().get(3).getCost(1)){
            baseGame.removeMoney(baseGame.getUpgradesList().get(3).getCost(1));
            baseGame.getUpgradesList().get(3).buyUpgrade(1);
            moneyBox.setText("gold: " + Integer.toString(baseGame.getMoney()));
            comboDescription.setText(baseGame.getUpgradesList().get(3).getDescription()+baseGame.getUpgradesList().get(3).getCost(1));
            if(baseGame.getUpgradesList().get(3).getTimesBought()>=3){
                comboButton.setEnabled(false);
            }
            
        }
    }//GEN-LAST:event_comboButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop(baseGame).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Armour;
    private javax.swing.JButton Damage;
    private javax.swing.JButton Health;
    private javax.swing.JTextPane armourDescription;
    private javax.swing.JTextField armourField;
    private javax.swing.JButton comboButton;
    private javax.swing.JTextPane comboDescription;
    private javax.swing.JTextPane damageDescription;
    private javax.swing.JTextField damageField;
    private javax.swing.JTextPane healthDescription;
    private javax.swing.JTextField healthField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField moneyBox;
    private javax.swing.JButton shopExit;
    // End of variables declaration//GEN-END:variables
}
